use_frameworks!

platform :ios, '8.0'

target 'WNJChannelEditController_Example' do
  pod 'WNJChannelEditController', :path => '../'

  target 'WNJChannelEditController_Tests' do
    inherit! :search_paths

    
  end
end
